level_four/fourth/urls.py
from fourth import views
from django.urls import path

# SET THE NAMESPACE!
app_name = 'fourth'

urlpatterns = [
    path('relative/',views.relative,name="relative"),
    path('other/',views.other,name="other"),
]

level_four/level_four/urls.py
from django.contrib import admin
from django.urls import path,include
from fourth import views

urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls,name="admin:index"),
    path('fourth/', include('fourth.urls'))
]

level_four/fourth/models.py
from django.db import models

# Create your models here.

level_four/fourth/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world', 'number':100}
    return render(request,'fourth/index.html',context_dict)


def other(request):
    return render(request,'fourth/other.html')


def relative(request):
    return render(request,'fourth/relative_url_templates.html')

level_four/templates/fourth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
   <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'fourth:other' %}">Other</a></li>
        </ul>
    </div>
   </nav>
   <div class="container">



    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>
</body>
</html>

level_four/templates/fourth/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome</title>
    </head>
    <body>
        <h1>Welcome to home page!</h1>

        {{ text|cut:'world' }}
        {{ number }}
    </body>
</html>

level_four/templates/fourth/other.html
<!DOCTYPE html>
{% extends "fourth/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>

    {% endblock %}

level_four/templates/fourth/relative_url_templates.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Page</title>
    </head>
    <body>
        <h1>Welcome to relative url templates!</h1>
        <a href="{% url 'fourth:other' %}">Navigation to the "other" page</a>
    </body>
</html>